import { FuseNavigationItem } from "@fuse/components/navigation";

export const defaultNavigation: FuseNavigationItem[] = [
  {
    id: "dashboard",
    title: "Dashboard",
    // subtitle: 'Daily updates',
    type: "basic",
    icon: "heroicons_solid:home",
    link: "/dashboard",
  },
  {
    id: "catalog",
    title: "Catalog",
    type: "collapsable",
    icon: "heroicons_solid:archive",
    children: [
      {
        id: "catalog.my-catalog",
        title: "My Catalog",
        type: "basic",
        icon: "heroicons_solid:archive",
        link: "/master/master-catalog",
      },
      {
        id: "catalog-log",
        title: "Catalog Logs",
        type: "basic",
        icon: "heroicons_outline:book-open",
        link: "/master/catalog-logs",
      },
    ],
  },
  {
    id: "manage-seller-user",
    title: "Seller User",
    type: "basic",
    icon: "heroicons_solid:user",
    link: "/master/seller-user",
  },
  {
    id: "manage-seller-role",
    title: "Seller Roles",
    type: "basic",
    icon: "heroicons_solid:shield-check",
    link: "/master/seller-role",
  },
  {
    id: "authorization-workflow",
    title: "Authorization Workflow",
    // subtitle: 'Amz auto-authorization',
    type: "basic",
    icon: "heroicons_solid:user",
    link: "/authorization-workflow",
  },
  {
    id: "shop",
    title: "Shop",
    // subtitle: 'Manage Shops',
    type: "basic",
    icon: "heroicons_solid:newspaper",
    link: "/master/portal",
  },
  {
    id: "manage-seller",
    title: "Seller",
    // subtitle: 'Manage and oversee sellers',
    type: "basic",
    icon: "heroicons_solid:user-group",
    link: "/master/seller",
  },
  {
    id: "manage-user",
    title: "User",
    // subtitle: 'Manage premises users',
    type: "basic",
    icon: "heroicons_solid:users",
    link: "/master/user",
  },
  {
    id: "manage-role",
    title: "Roles",
    // subtitle: 'Manage roles',
    type: "basic",
    icon: "heroicons_outline:lock-open",
    link: "/master/manage-role",
  },
  {
    id: "seller-store",
    title: "Seller Store",
    type: "basic",
    icon: "heroicons_solid:shopping-bag",
    link: "/master/seller-store",
  },
  {
    id: "admin-route-acl",
    title: "Admin API Access Control",
    type: "basic",
    icon: "heroicons_solid:shield-check",
    link: "/master/admin-route-acl",
  },
  {
    id: "seller-route-acl",
    title: "Seller API Access Control",
    type: "basic",
    icon: "heroicons_solid:shield-check",
    link: "/master/seller-route-acl",
  },
  {
    id: "features",
    title: "Features",
    type: "basic",
    icon: "heroicons_solid:cube",
    link: "/master/features",
  },
  {
    id: "feature-meter",
    title: "Feature Usage Meters",
    type: "basic",
    icon: "heroicons_solid:chart-bar",
    link: "/master/feature-meter",
  },
  {
    id: "manage-plan",
    title: "Plans",
    // subtitle: 'Manage plans',
    type: "basic",
    icon: "heroicons_outline:lock-open",
    link: "/master/manage-plan",
  },
  {
    id: "manage-contact",
    title: "Contact",
    type: "basic",
    icon: "heroicons_solid:mail",
    link: "/master/contact",
  },
  {
    id: "web-settings",
    title: "Web Settings",
    type: "basic",
    icon: "heroicons_outline:globe-alt",
    link: "/master/web-settings",
  },
  {
    id: "coupon",
    title: "Coupons",
    // subtitle: 'Manage coupons',
    type: "basic",
    icon: "heroicons_outline:ticket",
    link: "/master/coupon",
  },
  // {
  //     id: 'admin-inventory',
  //     title: 'Inventory',
  //     subtitle: 'View seller inventory',
  //     type: 'basic',
  //     icon: 'heroicons_solid:chart-bar',
  //     link: '/master/admin-inventory'
  // },
  {
    id: "amazon",
    title: "Amazon",
    icon: "heroicons_solid:chart-bar",
    type: "collapsable",
    imageurl: "assets/amazon-white.jpg",
    children: [
      {
        id: "amazon.inventory",
        title: "Inventory",
        icon: "heroicons_solid:chart-bar",
        type: "basic",
        link: "/master/amazon-inventory",
      },
      {
        id: "orders",
        title: "Orders",
        icon: "heroicons_outline:shopping-bag",
        type: "basic",
        link: "/master/orders",
      },
      {
        id: "compliance-setting",
        title: "Amazon Compliance",
        type: "collapsable",
        icon: "mat_solid:verified",
        children: [
          {
            id: "compliance-rules",
            title: "Compliance Rules",
            type: "basic",
            icon: "mat_solid:verified",
            link: "/master/amazon/compliance",
          },
          {
            id: "banned-items",
            title: "Banned Items",
            type: "basic",
            icon: "heroicons_outline:ban",
            link: "/master/amazon/compliance/banned-items",
          },
        ],
      },
      {
        id: "amz-inv-log",
        title: "Amazon Inv Logs",
        type: "basic",
        icon: "heroicons_outline:book-open",
        link: "/master/amazon/amz-inv-logs",
      },
    ],
  },
  {
    id: "uploaded-files",
    title: "Uploaded Files",
    type: "basic",
    icon: "heroicons_outline:document-report",
    link: "/master/uploaded-files",
  },
  {
    id: "tag-setting",
    title: "Tag Setting ",
    // subtitle: 'Manage Tags for inventory items',
    type: "basic",
    icon: "heroicons_solid:tag",
    link: "/master/tag-setting",
  },
  {
    id: "general-setting",
    title: "General Setting",
    // subtitle: 'Manage portal settings',
    type: "basic",
    icon: "mat_outline:settings",
    link: "/master/general-setting",
  },
  // ── Support ──────────────────────────────────────────────────────────────────
  {
    id: "support",
    title: "Support",
    type: "collapsable",
    icon: "heroicons_outline:support",
    children: [
      {
        id: "support.tickets",
        title: "Tickets",
        type: "basic",
        icon: "heroicons_outline:ticket",
        link: "/master/support/tickets",
      },
      {
        id: "support.faqs",
        title: "FAQs",
        type: "basic",
        icon: "heroicons_outline:question-mark-circle",
        link: "/master/support/faqs",
      },
      {
        id: "support.quick-replies",
        title: "Quick Replies",
        type: "basic",
        icon: "heroicons_solid:chat-alt",
        link: "/master/support/quick-replies",
      },
    ],
  },
  {
    id: "subscription",
    title: "Subscription",
    // subtitle: 'Manage subscription',
    type: "basic",
    icon: "heroicons_solid:credit-card",
    link: "/master/subscription",
  },
  {
    id: "system-log",
    title: "System Log",
    // subtitle: 'View system log',
    type: "basic",
    icon: "heroicons_outline:book-open",
    link: "/master/system-logs",
  },
  {
    id: "cron-management",
    title: "Cron Management",
    type: "basic",
    icon: "heroicons_outline:cog",
    link: "/master/cron-management",
  },
  {
    id: "cron-logs",
    title: "Cron Logs",
    type: "basic",
    icon: "heroicons_outline:clock",
    link: "/master/cron-logs",
  },

  {
    id: "technical-document",
    title: "Technical Document",
    type: "basic",
    icon: "heroicons_outline:document-text",
    link: "/master/technical-doc",
  },
  // {
  //   id: "guide-documents.admin",
  //   title: "Manage Guide Docs",
  //   type: "basic",
  //   icon: "heroicons_outline:cog",
  //   link: "/master/guide-documents",
  // },
  {
    id: "guide-documents",
    title: "Guide Documents",
    type: "basic",
    icon: "heroicons_outline:book-open",
    link: "/master/guide-documents/viewer",
  },
  {
    id: "blogs",
    title: "Blogs",
    type: "basic",
    icon: "heroicons_outline:document-text",
    link: "/master/blogs",
  },
];
